skills = ["python",
    "java",
    "c++",
    "sql",
    "machine learning",
    "deep learning",
    "fastapi",
    "django",
    "flask",
    "data analysis",
    "nlp",
    "docker",
    "aws",
    "git",
    "postgresql"]