skills = ["python",
    "java",
    "c++",
    "sql",
    "machine learning",
    "deep learning",
    "fastapi",
    "django",
    "flask",
    "data analysis",
    "nlp",
    "docker",
    "aws",
    "git",
    "postgresql",
    "mongodb",
    "html",
    "css",
    "javascript",
    "react",
    "node.js",
    "agile",
    "scrum",
    "rest",
    "graphql",
    "kubernetes",
    "tensorflow",
    "pytorch",
    "linux",
    "bash",
    "ci/cd",
    "jupyter",
    "tableau",
    "power bi"
    "ruby",
    "php",
    "swift",
    "go",
    "r",
    "matlab",
    "hadoop",
    "spark",
    "etl",
    "data visualization",
    "big data",
    "cybersecurity",
    "blockchain",
    "devops",
    "microservices",
    "rest api",
    "unit testing",
    "integration testing",
    "performance optimization",
    "cloud computing",
    "virtualization",
    "networking",
    "object-oriented programming",
    "functional programming",
    "data structures",
    "algorithms",
    "version control",
    "software development lifecycle",
    "project management",
    "ui/ux design",
    "mobile development",
    "game development",
    "embedded systems",
    "robotics",
    "internet of things",
    "artificial intelligence",
    "computer vision",
    "data mining",
    "predictive modeling",
    "statistical analysis",
    "time series analysis",
    "natural language processing",
    "reinforcement learning",
    "cloud services",
    "serverless computing",
    "infrastructure as code",
    "monitoring and logging",
    "incident management",
    "disaster recovery",
    "compliance and security",
    "performance tuning",
    "scalability",
    "load balancing",
    "high availability",
    "data governance",
    "data warehousing",
    "etl processes",
    "data lakes",
    "data pipelines",
    "data engineering",
    "agile methodologies",
    "scrum framework",
    "kanban",
    "lean software development",
    "continuous integration",
    "continuous deployment",
    "test-driven development",
    "behavior-driven development",
    "pair programming",
    "code reviews",
    "software architecture",
    "design patterns",
    "system design",
    "performance engineering",
    "technical writing",
    "team collaboration",
    "leadership",
    "communication skills",
    "problem-solving",
    "critical thinking",
    "time management",
    "adaptability",
    "creativity",
    "attention to detail",
    "customer service",
    "business analysis",
    "stakeholder management",
    "negotiation skills",
    "conflict resolution",
    "presentation skills",
    "public speaking",
    "mentoring",
    "coaching",
    "training and development",
    "emotional intelligence"]